name: build caddy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
    - uses: actions/checkout@v3
    - name: go caddy and build caddy
      run: | 
        cd caddy
        docker build . --file Dockerfile --tag luckysnow/caddy:latest
    - name: push  caddy
      run: docker push luckysnow/caddy:latest
