name: build nginx-webdav

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Docker login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
    - uses: actions/checkout@v3
    - name: build nginx-webdav
      run: | 
        cd nginx-webdav/base-nginx
        curl -o Dockerfile https://raw.githubusercontent.com/nginx/docker-nginx/master/modules/Dockerfile
        sed -i 's/libxml2-utils/libxml2-utils libxml2 libxslt-dev/g' Dockerfile
        sed -i 's/    apt-get update \\/    apt-get update \\\n    \&\& apt-get install -y  apache2-utils \\/g'  Dockerfile
        mkdir dav_ext_methods
        echo "https://github.com/arut/nginx-dav-ext-module/archive/refs/tags/v3.0.0.tar.gz" > dav_ext_methods/source
        docker compose up --build -d
        cd ..
        docker build . --file Dockerfile --tag luckysnow/nginx-webdav:latest
    - name: push nginx-webdav
      run: docker push luckysnow/nginx-webdav:latest
